### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by alonfnt** [AlbertAlonso/PhotonTheme#1]
![Colors Pallete](https://user-images.githubusercontent.com/38870744/59663610-aed4d980-91af-11e9-83bc-5271285e6445.png)

**Comment by alonfnt** [comment]
The initial implementation is:

![GxBFLQG5bU](https://user-images.githubusercontent.com/38870744/59675650-fb2b1400-91c5-11e9-981e-1a2737a17918.png)

But I am happy to discuss more possible colors to add to the collection.

**Comment by MairwunNx** [comment]
@AlbertAlonso Based on this, you can say that you made colors only for light themes. This issue should remain until you come up with dark theme colors.

**Comment by alonfnt** [comment]
@MairwunNx  you are right! The idea was to set a collection of colors to use as reference so later on theming can be done more easily.
