### ISSUE TITLE
Typography

### ISSUE THREAD

**Issue by alonfnt** [AlbertAlonso/PhotonTheme#2]
![Typography](https://user-images.githubusercontent.com/38870744/59663657-cb711180-91af-11e9-8343-c7262fe0c57d.png)

**Comment by alonfnt** [comment]
The current implemetation is:

![PhotonDesign DemoWpf_N1kHTYAYT1](https://user-images.githubusercontent.com/38870744/59675468-9a034080-91c5-11e9-883b-08c40f29f02f.png)

I am not sure having a bold version is really needed. But maybe we can expand the different types. I am open to suggestions.

**Comment by MairwunNx** [comment]
Also before implementation Typography section, make sure what it font support cyrillic characters. (`АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ`)

**Comment by alonfnt** [comment]
@MairwunNx Would you say it supports it? I don't use the cyrillic alphabet so I'm not sure if any letter is wrong. Thanks for the heads up. 

![EVwXjEJIdJ](https://user-images.githubusercontent.com/38870744/61665437-465ca900-acd5-11e9-94ab-0e11710409c1.png)


The style seems to be consistent with the other fonts, although it could be a bit bolder. Thoughts?

**Comment by MairwunNx** [comment]
@AlbertAlonso Yes, everything is fine, since it looks the same - it means it **is supported**.
